"""
interview_engine.py
====================
Adaptive, persona-driven interview engine.

PERSONA
-------
Senior tech interviewer. Dry. Sharp. Slightly sarcastic when a candidate
hand-waves. Deeply technical. Never moves on from a topic until the candidate
has demonstrated they actually understand it — or has clearly failed to.

DYNAMIC FLOW
------------
Every candidate answer is assessed for quality. The engine routes the next
turn based on that assessment, NOT on a rigid question sequence:

  GOOD answer   → advance to the next planned question.
  VAGUE / BRIEF → inject a sharp follow-up on the SAME topic before advancing.
  HANDWAVE      → inject a sarcastic, targeted counter before advancing.
  WEAK STREAK   → escalate tone; compress remaining plan.

A topic is drilled at most once (one follow-up max) so the interview doesn't
get stuck in an infinite loop. After a drill, the engine always moves forward.

MOCK MODE
---------
MOCK_MODE = True  → Each planned question also carries a simulated candidate
                    reply so you can drive the full flow from a test script
                    without typing. Replies are intentionally messy.

Set MOCK_MODE = False and implement _llm_reply() when wiring real AI.

TECHNICAL SPEC COMPLIANCE
--------------------------
- POST /api/interview maintained via main.py
- sessionId, 8+ questions / 4+ days enforced by question_generator.py
- Final FeedbackPayload (summary, strengths, gaps, next) produced by build_feedback()
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from enum import Enum
from typing import Optional

from models import Candidate, FeedbackPayload
from question_generator import InterviewQuestion, QuestionType
from session_store import (
    get_session,
    get_current_question,
    advance_question,
    append_history,
    mark_done,
    inject_followup,
    pop_followup,
    has_pending_followup,
    is_current_q_probed,
    record_turn,
    get_weak_streak,
    get_weak_turn_count,
)

# ---------------------------------------------------------------------------
# Global toggle
# ---------------------------------------------------------------------------
MOCK_MODE: bool = True


# ===========================================================================
# SYSTEM PROMPT  (ready to be inserted as LLM system message)
# ===========================================================================

INTERVIEWER_PERSONA: str = """
You are a senior technical interviewer conducting a rigorous debrief of a
candidate who just completed a 31-day AI engineering cohort.

PERSONA
-------
- You have 15+ years building production AI systems.
- You have seen every variety of BS: textbook recitation, tutorial parroting,
  vague buzzword salad, and "it just worked" non-answers.
- Your tone is dry, precise, and slightly sarcastic when a candidate
  hand-waves — but you are fair and genuinely reward clear, honest thinking.
- You NEVER let a weak answer slide. If the answer is vague, you push.
  If it's a textbook quote, you ask about the edge cases. If it's too short,
  you ask them to elaborate on the hardest part. If it mentions a tool without
  explaining WHY that tool, you ask why not the obvious alternative.

RULES
-----
1. Never ask a generic follow-up. Every counter must be grounded in the
   specific tool, objective, or trade-off from that curriculum day.
2. If the candidate says "I followed the tutorial" or "it just worked",
   respond with mild sarcasm and then drill into the specific mechanism:
   "Glad the tutorial was useful. Now tell me what actually happens when
   [specific failure mode or edge case]."
3. If the answer is too short (< 3 sentences), ask them to be more specific:
   "That's a start. Walk me through the specific step where you hit a wall."
4. If the answer is good, acknowledge it briefly and move to the next topic.
   Do not over-praise. One short sentence max.
5. Never ask more than one follow-up per topic (you have limited time).
6. Always ground your next question in the curriculum day's actual objectives
   and tools — not generic AI interview questions.
7. End the interview with a clean, professional closing when all topics
   have been covered.

OUTPUT FORMAT
-------------
Reply with plain text only. No markdown in the question itself.
The question number label [Qn — Day X: Title] is generated by the system.
""".strip()


# ===========================================================================
# ANSWER QUALITY ASSESSMENT
# ===========================================================================

class AnswerQuality(str, Enum):
    GOOD      = "good"       # substantive, specific, technical
    VAGUE     = "vague"      # conceptually aware but no specifics
    BRIEF     = "brief"      # too short to assess
    HANDWAVE  = "handwave"   # buzzwords / tutorial references / non-answer


# Phrases that signal the candidate is parroting without real understanding
_HANDWAVE_PHRASES: list[str] = [
    "followed the tutorial",
    "just followed",
    "it just worked",
    "it worked",
    "pretty straightforward",
    "easy enough",
    "not really sure",
    "kind of",
    "sort of just",
    "basically just",
    "I think maybe",
    "I guess",
    "something like that",
    "I don't remember exactly",
    "more or less",
    "just ran the code",
    "copy pasted",
    "used the example",
    "took the sample",
]

# If the answer is shorter than this many words it's flagged BRIEF
_BRIEF_WORD_THRESHOLD = 35

# Vagueness patterns: mentions concepts but no concrete details
_VAGUE_PATTERNS: list[str] = [
    r"\b(vectors?|embeddings?|models?|agents?|pipelines?)\b.{0,60}$",  # topic noun, nothing after
    r"^[^.]{0,120}\.$",   # single short sentence
]


def assess_answer_quality(answer: str, question: InterviewQuestion) -> AnswerQuality:
    """
    Rule-based quality classifier.
    Returns HANDWAVE > BRIEF > VAGUE > GOOD in order of severity.
    """
    text  = answer.strip()
    lower = text.lower()
    words = text.split()

    # Check handwave phrases first (highest priority flag)
    if any(p in lower for p in _HANDWAVE_PHRASES):
        return AnswerQuality.HANDWAVE

    # Too short
    if len(words) < _BRIEF_WORD_THRESHOLD:
        return AnswerQuality.BRIEF

    # Vague: mentions the right domain words but no tool names or specific steps
    day_tools_lower = [t.lower() for t in (question.tools if hasattr(question, "tools") else [])]
    tool_mentioned  = any(t in lower for t in day_tools_lower) if day_tools_lower else True

    # Heuristic: if it's a DEPTH_VERIFY question and no tool name appears → vague
    if question.question_type == QuestionType.DEPTH_VERIFY and not tool_mentioned:
        return AnswerQuality.VAGUE

    # Count sentences as a proxy for elaboration
    sentence_count = len(re.split(r'[.!?]+', text))
    if sentence_count < 3:
        return AnswerQuality.VAGUE

    return AnswerQuality.GOOD


# ===========================================================================
# SHARP FOLLOW-UP GENERATOR  (persona in action)
# ===========================================================================

# Each template receives keyword args: day_title, tool, objective, attempts
_FOLLOWUP_TEMPLATES: dict[AnswerQuality, list[str]] = {

    AnswerQuality.HANDWAVE: [
        (
            "Glad the {tool} tutorial exists. But tutorials are written for happy paths. "
            "Tell me what happens when {objective_challenge} — "
            "what breaks first, and how would you catch it before it hits production?"
        ),
        (
            "\"It worked\" is doing a lot of heavy lifting there. "
            "Walk me through specifically what *{tool}* is actually doing under the hood "
            "when you call it for this task. What would a wrong output look like, "
            "and how would you know?"
        ),
        (
            "Right. And if I put that code in front of a code reviewer who's never seen "
            "this cohort, what's the one thing they'd push back on immediately? "
            "Be specific about {day_title}."
        ),
        (
            "You said it \"just worked.\" In my experience, things that just work "
            "are things we don't fully understand yet. "
            "What's the most likely failure mode of your {day_title} implementation "
            "at 10x the data volume?"
        ),
    ],

    AnswerQuality.BRIEF: [
        (
            "That's a start. You've given me the \"what\" — I need the \"how\" and the \"why\". "
            "Walk me through the specific step in {day_title} where you hit resistance "
            "and what decision you made to get past it."
        ),
        (
            "Too short. You've described the outcome. I want to understand your reasoning. "
            "When you were working on {day_title}, what was the trade-off you had to make "
            "that wasn't spelled out in the objective? What did you sacrifice to get it done?"
        ),
        (
            "I appreciate the brevity but this isn't a stand-up. "
            "Tell me the one specific thing about {day_title} that you'd do "
            "differently if you were building it for a real enterprise system."
        ),
    ],

    AnswerQuality.VAGUE: [
        (
            "You've described the concept correctly — every candidate who read the docs can do that. "
            "I want to know what *you* specifically did with {tool} during {day_title}. "
            "What parameter, config, or architectural choice did you make that wasn't default?"
        ),
        (
            "That explanation would pass a multiple-choice quiz. "
            "Let's get concrete: when you ran {tool} on the actual mission data, "
            "what was the first output that surprised you, and what did it tell you "
            "about how the system actually behaves?"
        ),
        (
            "You clearly understand the theory. Here's the test: "
            "if your {day_title} implementation silently returned wrong results "
            "with no error — no exception, no crash — how would you detect it? "
            "What does your validation look like?"
        ),
    ],
}


def _generate_followup(
    quality: AnswerQuality,
    question: InterviewQuestion,
    weak_streak: int,
) -> str:
    """
    Pick and render a sharp follow-up for the given quality signal.
    Escalates sarcasm level if weak_streak > 1.
    """
    import random

    templates = _FOLLOWUP_TEMPLATES.get(quality, _FOLLOWUP_TEMPLATES[AnswerQuality.VAGUE])
    template  = random.choice(templates)

    tools     = getattr(question, "tools", [])
    tool_str  = tools[0] if tools else question.day_title
    objectives = getattr(question, "objectives", [])
    obj_challenge = objectives[-1] if objectives else f"the system fails mid-{question.day_title}"

    text = template.format(
        day_title=question.day_title,
        tool=tool_str,
        objective_challenge=obj_challenge,
    )

    # Escalate prefix for persistent weak streaks
    if weak_streak >= 2:
        prefix = (
            "I'm going to push on this again because the last two answers haven't "
            "convinced me you've actually built this. "
        )
        text = prefix + text

    return text


# ===========================================================================
# DISPLAY HELPERS
# ===========================================================================

_TYPE_LABELS: dict[QuestionType, str] = {
    QuestionType.DEPTH_VERIFY: "Depth Verification",
    QuestionType.PROBE:        "Struggle Probe",
    QuestionType.COUNTER:      "Counter Question",
    QuestionType.EXPLORE:      "Gap Exploration",
    QuestionType.FAILED:       "Understanding Check",
}


def _format_planned_question(q: InterviewQuestion, number: int) -> str:
    label = _TYPE_LABELS.get(q.question_type, "Question")
    tag   = f"[{label} — Day {q.day}: {q.day_title}]"
    return f"**Q{number}** {tag}\n\n{q.text}"


def _format_followup(text: str, number: int, quality: AnswerQuality) -> str:
    quality_labels = {
        AnswerQuality.HANDWAVE: "Sharp Counter",
        AnswerQuality.BRIEF:    "Elaboration Probe",
        AnswerQuality.VAGUE:    "Precision Drill",
    }
    label = quality_labels.get(quality, "Follow-up")
    tag   = f"[{label} — Drilling previous answer]"
    return f"**Q{number}** {tag}\n\n{text}"


# ===========================================================================
# WELCOME
# ===========================================================================

def build_welcome(candidate: Candidate, first_question: InterviewQuestion) -> str:
    name      = candidate.member.name
    role      = candidate.member.jobRole
    completed = candidate.signals.missionsCompleted
    first_try = candidate.signals.missionsFirstTry
    yoe       = candidate.member.yearsExperience

    # Persona-aware opener — drier, more direct
    intro = (
        f"Alright, {name}. Let's get into it.\n\n"
        f"I've looked at your profile — {role}, {yoe} year(s) of experience, "
        f"{candidate.member.education}. "
        f"You finished {completed} missions in the cohort with {first_try} "
        f"first-try passes, which is {'solid' if first_try >= 15 else 'something we should talk about'}.\n\n"
        f"I'm not going to ask you to define embeddings or recite RAG steps. "
        f"I've read the curriculum. What I want to know is whether you actually built "
        f"things, hit walls, and understood why they fell over.\n\n"
        f"We'll move through topics based on your specific mission history. "
        f"If your answer is too short or too neat, I'll push. Fair warning.\n\n"
        f"---\n\n"
        f"{_format_planned_question(first_question, 1)}"
    )
    return intro


# ===========================================================================
# CORE TURN PROCESSOR
# ===========================================================================

def process_turn(session_id: str, candidate_message: str) -> tuple[str, bool]:
    """
    Adaptive turn processor.

    Decision tree per turn:
      1. Assess quality of candidate_message.
      2a. If quality is GOOD → advance to next planned question.
      2b. If quality is weak AND current topic not yet probed
              → inject a sharp follow-up; do NOT advance yet.
      2c. If quality is weak AND topic already probed (one drill done)
              → advance anyway (we don't loop forever).
      3. If no more planned questions → close the interview.
    """
    session      = get_session(session_id)
    plan         = session["question_plan"]
    current_q    = get_current_question(session_id)

    # Store candidate answer
    append_history(session_id, "candidate", candidate_message)

    # --- Assess quality -------------------------------------------------------
    quality = assess_answer_quality(candidate_message, current_q) if current_q else AnswerQuality.GOOD
    is_weak = quality in (AnswerQuality.HANDWAVE, AnswerQuality.BRIEF, AnswerQuality.VAGUE)
    record_turn(session_id, was_weak=is_weak)
    weak_streak = get_weak_streak(session_id)

    # --- Route: follow-up vs advance -----------------------------------------
    already_probed = is_current_q_probed(session_id)

    if is_weak and not already_probed and current_q is not None:
        # Inject a sharp follow-up; stay on same topic
        followup_text = _generate_followup(quality, current_q, weak_streak)
        inject_followup(session_id, followup_text)

        # Compute display question number (total turns so far)
        q_number = session["total_turns"] + 1
        reply    = _format_followup(followup_text, q_number, quality)
        append_history(session_id, "interviewer", reply)
        return reply, False

    # Answer was good (or we already probed once) → advance
    advance_question(session_id)
    new_idx  = session["current_q_index"]
    q_number = session["total_turns"] + 1

    # No more planned questions → end
    if new_idx >= len(plan):
        mark_done(session_id)
        closing = _build_closing(session_id)
        append_history(session_id, "interviewer", closing)
        return closing, True

    # Ask next planned question
    next_q = plan[new_idx]
    reply  = _format_planned_question(next_q, q_number)

    # Brief acknowledgement prefix for good answers (one line, no over-praise)
    if not is_weak:
        reply = _good_answer_ack(quality) + "\n\n" + reply

    append_history(session_id, "interviewer", reply)
    return reply, False


def _good_answer_ack(quality: AnswerQuality) -> str:
    """Short, dry acknowledgement. No gold stars."""
    import random
    acks = [
        "Good. Let's keep moving.",
        "That checks out.",
        "Okay, I'll take that.",
        "Right. Moving on.",
        "Fair enough.",
        "That's the kind of specificity I'm looking for. Next topic.",
    ]
    return random.choice(acks)


def _build_closing(session_id: str) -> str:
    weak_count = get_weak_turn_count(session_id)
    total      = get_session(session_id)["total_turns"]
    ratio      = weak_count / total if total > 0 else 0

    if ratio > 0.5:
        tone = (
            "That was a mixed session — a number of your answers needed pushing. "
            "I'll reflect that in the feedback."
        )
    elif ratio > 0.25:
        tone = (
            "There were a few spots where I had to dig, but overall you showed "
            "reasonable depth across the topics we covered."
        )
    else:
        tone = (
            "Solid interview. You answered specifically and technically, "
            "which is exactly what I'm looking for."
        )

    return (
        f"{tone}\n\n"
        f"We covered {total} turns across the key curriculum areas from your history. "
        f"I'll compile the feedback now."
    )


# ===========================================================================
# FEEDBACK BUILDER
# ===========================================================================

def build_feedback(session_id: str) -> FeedbackPayload:
    session   = get_session(session_id)
    candidate = session["candidate"]
    plan      = session["question_plan"]

    missions_passed  = [m for m in candidate.missions if m.passed is True]
    missions_skipped = [m for m in candidate.missions if m.skipped]
    missions_failed  = [m for m in candidate.missions if m.passed is False]
    high_attempt     = [m for m in missions_passed if (m.attempts or 0) >= 4]

    total_turns = session["total_turns"]
    weak_count  = get_weak_turn_count(session_id)
    weak_ratio  = weak_count / total_turns if total_turns > 0 else 0

    depth_qs   = [q for q in plan if q.question_type == QuestionType.DEPTH_VERIFY]
    explore_qs = [q for q in plan if q.question_type == QuestionType.EXPLORE]

    strengths: list[str] = []
    gaps:      list[str] = []
    next_steps: list[str] = []

    # --- Strengths ---
    if candidate.signals.commitDays >= 25:
        strengths.append(
            f"Sustained engagement: {candidate.signals.commitDays} active days "
            f"demonstrates consistent work ethic throughout the 31-day cohort."
        )
    if candidate.signals.missionsFirstTry >= 15:
        strengths.append(
            f"High first-attempt accuracy: {candidate.signals.missionsFirstTry}/"
            f"{candidate.signals.missionsCompleted} missions passed first try — "
            f"indicates strong problem-solving approach and low rework rate."
        )
    elif candidate.signals.missionsFirstTry >= 8:
        strengths.append(
            f"Reasonable first-attempt rate ({candidate.signals.missionsFirstTry}/"
            f"{candidate.signals.missionsCompleted}) — shows deliberate preparation "
            f"before submitting solutions."
        )
    if len(missions_passed) >= 8:
        strengths.append(
            f"Broad coverage: {len(missions_passed)} missions completed across "
            f"multiple modules spanning data foundations to production deployment."
        )
    if weak_ratio < 0.25 and total_turns >= 5:
        strengths.append(
            f"Interview performance: answered with technical specificity across "
            f"{total_turns} turns — rarely required prompting for elaboration."
        )
    if not strengths:
        strengths.append(
            "Demonstrated persistence in completing the AI cohort despite significant "
            "difficulty across multiple mission areas."
        )

    # --- Gaps (informed by interview performance + mission history) ---
    if weak_ratio >= 0.5:
        gaps.append(
            f"Communication of technical depth: {weak_count}/{total_turns} interview turns "
            f"required follow-up prompting to elicit specific technical detail. "
            f"Candidate tends toward high-level answers without unprompted elaboration."
        )
    elif weak_ratio >= 0.25:
        gaps.append(
            f"Inconsistent depth in explanations: {weak_count} turns required drilling — "
            f"candidate is stronger on some topics than others."
        )
    if missions_skipped:
        titles = ", ".join(m.title for m in missions_skipped)
        gaps.append(
            f"Unverified areas from skipped missions: {titles}. "
            f"Gap exploration questions confirmed limited hands-on exposure."
        )
    if missions_failed:
        titles = ", ".join(m.title for m in missions_failed)
        gaps.append(
            f"Incomplete missions with outstanding knowledge gaps: {titles}. "
            f"Candidate acknowledged gaps when directly questioned."
        )
    if high_attempt:
        titles = ", ".join(m.title for m in high_attempt[:3])
        gaps.append(
            f"Persistent difficulty areas (4+ attempts): {titles}. "
            f"Struggle probe questions revealed underlying conceptual confusion "
            f"rather than simple implementation bugs."
        )
    if not gaps:
        gaps.append(
            "No critical gaps identified. Candidate demonstrated solid technical "
            "depth and honest self-assessment across all assessed areas."
        )

    # --- Next steps ---
    if weak_ratio >= 0.4:
        next_steps.append(
            "Practice articulating technical decisions out loud. The ability to explain "
            "not just what you did but WHY — and what could go wrong — is non-negotiable "
            "at the senior level."
        )
    if missions_skipped:
        next_steps.append(
            "Complete the skipped missions hands-on (not just read about them). "
            "Specifically: production deployment and security modules are "
            "table-stakes for any AI engineering role."
        )
    if missions_failed:
        next_steps.append(
            "Revisit failed missions by building a minimal standalone implementation "
            "from scratch — no starter code. Failure to pass under exam conditions "
            "usually means the mental model is wrong, not just the code."
        )
    if high_attempt:
        next_steps.append(
            "For topics that took 4+ attempts, build a side project that uses that "
            "concept as its core mechanism. Passive review will not fix a broken "
            "mental model."
        )
    next_steps.append(
        "Ship a production-grade AI project end-to-end: RAG retrieval, agent "
        "orchestration, deployment, and monitoring. Portfolio evidence matters "
        "more than cohort completion at the hiring stage."
    )
    next_steps.append(
        "Read the failure modes, not just the success paths. For every tool you "
        "used in this cohort, study: what makes it slow, what makes it fail silently, "
        "and what the production-safe alternative looks like."
    )

    # Summary
    q_days = len(set(q.day for q in plan))
    interview_quality = (
        "strong" if weak_ratio < 0.25
        else "mixed" if weak_ratio < 0.5
        else "below expectations"
    )
    summary = (
        f"{candidate.member.name} ({candidate.member.jobRole}, "
        f"{candidate.member.yearsExperience} yrs exp, {candidate.member.education}) "
        f"completed the AI cohort with {candidate.signals.missionsCompleted} missions, "
        f"{candidate.signals.commitDays} active days, and a "
        f"{candidate.signals.missionsFirstTry}/{candidate.signals.missionsCompleted} "
        f"first-try rate. "
        f"The interview covered {total_turns} turns across {q_days} curriculum days "
        f"with {weak_count} turns requiring follow-up probing. "
        f"Overall interview performance: {interview_quality}. "
        f"{'Recommend for next round with technical coding challenge.' if weak_ratio < 0.35 else 'Recommend a second technical screen before advancing.'}"
    )

    return FeedbackPayload(
        summary=summary,
        strengths=strengths,
        gaps=gaps,
        next=next_steps,
    )
